name: KICS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 08 * * 1'

permissions:
  contents: read

jobs:
  kics_job:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-22.04
    name: KICS Job
    steps:
      - uses: actions/checkout@v3
      - name: run kics Scan
        uses: checkmarx/kics-github-action@v2.1.3
        with:
          path: 'terraform,cfn-templates,my-other-sub-folder/Dockerfile'
          output_path: myResults/
      - name: display kics results
        run: |
          cat myResults/results.json