name: semgrep

on:
    workflow_dispatch: {}
    pull_request: {}
    push:
      branches:
      - master
    schedule:
    - cron: "0 8 * * *" # run once a day at 8 AM

jobs:
    semgrep:
      name: semgrep/ci
      runs-on: ubuntu-22.04
      env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        SEMGREP_APP_URL: https://dev2.semgrep.dev
      container:
        image: returntocorp/semgrep
      steps:
      - uses: actions/checkout@v4
      - run: semgrep ci